### PR TITLE
Reward calculation after done condition

### PR DESCRIPTION
**Pull request by Olloxan**
Hi, 
reward calculation of sokoban levels was not done correctly when level "timed out" (steps > max_stpes). If level is completed correctly with all boxes on box targets, reward should be +10, but if the level is completed by maxsteps, the reward should be 0. So I have separeted the these conditions into a "done" condition whitch means the level is done be placing the boxes correctly and a "timedout" condition whitch means, level was completed by maxsteps.

best regards

### CODE REVIEW

**Comment by mpSchrader** [comment]
Hi @Olloxan,
thank you for your pull request.
Isn't already this done by [sokoban_env.py line 75](https://github.com/mpSchrader/gym-sokoban/blob/7a060f30c74858a9955882b9ba15d9839ad1b109/gym_sokoban/envs/sokoban_env.py#L175)?

**Comment by Olloxan** [comment]
unfortunately not. The line of code you pointed out does not distinguish between the two cases of ending a level. I noticed it when I was watching the rewards of my agent. It always got +10 when ending a level with steps > max_steps. Somehow the average rewards after 5000 epochs of training were always -2.00 . I keep trying ;)

**Comment by mpSchrader** [comment]
From my point of view the game is ending at the right point in time, right?
So you expect an reward of zero if the num_steps > max_steps, right? This just has to be done in the _calc_reward()-Function.
But why would the environment be used if done has been returned?
________________________________

**Comment by Olloxan** [comment]
ok, maybe "timeout" is not the best term to describe how the level ends.
lets summarize:

Performe Step : -0.1
Push Box on Target : 1.0
Push Box off Target : -1.0
Push all boxes on targets : 10.0 (ending the game)

if the agent has not pushed all boxes on the targets after "max_steps" (120) the game also ends, but without the reward of 10.0. 

Currently in function "step(self, action)", the reward is calculated, the game is checked, if it is finished, and if it´s finished, an additional reward is addded to the total reward
`self._calc_reward()
        done = self._check_if_done()

        if done:
               self.reward_last += self.reward_finished`

Maybe a function called "_check_if_all_boxes_on_target()" should be called inside "_calc_reward()" to determine, if the game was finished by placing all the boxes on the targets and be used only to calculate the reward. Function "_check_if_done()" could then be used like before with

`return done or (np.where(empty_targets | player_on_target)[0].shape[0] == 0)` 

but without 

` if done:
       self.reward_last += self.reward_finished`

in function "step(self, action)"

I am going to commit the code to show you what I mean.

**Comment by mpSchrader** [comment]
Now I see what you mean! Thank you!
________________________________

**Comment by Olloxan** [comment]
after testing the rewards caculation seems to be correct.

**Pull request merged**
